export { default as HomepageFrame } from './homepage/homepage-frame/homepage-frame.component' 
export { default as HomepageAboutUs } from './homepage/homepage-about-us/homepage-about-us.component' 
export { default as HomepageContact } from './homepage/homepage-contact/homepage-contact.component' 
export { default as HomepageLanding } from './homepage/homepage-landing/homepage-landing.component' 
export { default as HomepageProcess } from './homepage/homepage-process/homepage-process.component' 
export { default as HomepageProjects } from './homepage/homepage-projects/homepage-projects.component' 
